version: '3'
services:
  chainlit:
    build: .
    ports:
      - "8000:8000"
    restart: always
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}  # Pass your OpenAI API key
      # Add any Gemini API keys if needed
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      # If using authentication
      # - CHAINLIT_AUTH_SECRET=your_secret_here
      # - CHAINLIT_URL=https://your-domain.com
    volumes:
      # For development - mount your code so changes are reflected without rebuilding
      - ./.chainlit:/app/.chainlit